# Add the real_ip_header and X-Forwarded-For header for fail2ban
#
# 1. place this file into: /etc/nginx/conf.d 
#
# 2. Verify that the http_realip_module is built into nginx:
# nginx -V | grep with-http_realip_module
#
# 3. Populate set_real_ip_from with the trusted proxy/server IP address
#
# 4. Verify syntax with: 
# nginx -t
#
# 5. if everything is OK, restart nginx to activate real_ip_header and X-Forwarded-For
# systemctl restart nginx
#
set_real_ip_from __REAL_IP_FROM__;
real_ip_header X-Forwarded-For;
#
# --- eof ---
# vim: syntax=auto ts=4 sw=4 sts=4 sr noet
