# File: /etc/fail2ban/filter.d/grommunio-web-auth.conf
# Fail2Ban grommunio-web-auth filter
# (c) 2021 by Walter@Hofstaedtler.com
# Stored in WHIE GIT: git@icc-srv:/whie/grommunio/fail2ban.git

[INCLUDES]
before = common.conf

[Definition]
# Option:  failregex
# Notes.:  regex to match the password failures messages in the logfile. The
#          host must be matched by a group named "host". The tag "<HOST>" can
#          be used for standard IP/hostname matching and is only an alias for
#          (?:::f{4,6}:)?(?P<host>[\w\-.^_]+)
# Values:  TEXT
#
#
# failregex = \].\[<HOST>\].grommunio Web user:.* authentication failure at MAPI
# Seams grommunio 2.9 cahnged the error messages.
failregex = authentication failure at MAPI * client:.<HOST>

ignoreregex =

#[Init]
#journalmatch = _SYSTEMD_UNIT=nginx.service

# --- eof ---
# vim: syntax=auto ts=4 sw=4 sts=4 sr noet