# File: /etc/fail2ban/filter.d/grommunio-pop3.conf
# Fail2Ban grommunio-pop3 filter
# (c) 2024 by Walter@Hofstaedtler.com
# Stored in WHIE GIT: git@icc-file:/whie/grommunio/fail2ban.git

[INCLUDES]
before = common.conf

[Definition]

## _daemon = pop3
# Option:  failregex
# Notes.:  regex to match the password failures messages in the logfile. The
#          host must be matched by a group named "host". The tag "<HOST>" can
#          be used for standard IP/hostname matching and is only an alias for
#          (?:::f{4,6}:)?(?P<host>[\w\-.^_]+)
# Values:  TEXT
#
# standard and reverse proxy
failregex = rhost=\[\S+f:(<HOST>)\]\S* user=(\S+)@.*(auth|login|logon|LOGIN).* rejected:

ignoreregex =

[Init]
journalmatch = _SYSTEMD_UNIT=gromox-pop3.service

# --- eof ---
# vim: syntax=auto ts=4 sw=4 sts=4 sr noet
