# Fail2Ban filter for postfix authentication failures
#

[INCLUDES]

before = common.conf

[Definition]

#_daemon = postfix(-\w+)?/(?:submission/|smtps/)?smtp[ds]
_daemon = postfix/smtpd

#                                                                warning: unknown[92.118.38.39]: SASL LOGIN authentication failed: authentication failure
# Oct 28 16:07:36 static-spamd1.kunde.local postfix/smtpd[4301]: warning: unknown[80.94.95.181]: SASL LOGIN authentication failed: authentication failure
#
failregex = ^%(__prefix_line) warning: [-._\w]+\[<HOST>\]: SASL LOGIN authentication failed: authentication failure
### failregex = ^%(__prefix_line)swarning: [-._\w]+\[<HOST>\]: SASL ((?i)LOGIN|PLAIN|(?:CRAM|DIGEST)-MD5) authentication failed(:[ A-Za-z0-9+/:]*={0,2})?\s*$
### failregex = (?i): warning: [-._\w]+\[<HOST>\]: SASL (?:LOGIN|PLAIN|(?:CRAM|DIGEST)-MD5) authentication failed
### failregex = (?i): warning: [-._\w]+\[<HOST>\]: SASL (?:LOGIN|PLAIN|(?:CRAM|DIGEST)-MD5) authentication failed: 
### failregex = : warning: [-._\w]+\[<HOST>\]: SASL (?:LOGIN|PLAIN|(?:CRAM|DIGEST)-MD5) authentication failed
#failregex = ^%(__prefix_line)swarning: [-._\w]+\[<HOST>\]: SASL ((?i)LOGIN|PLAIN|(?:CRAM|DIGEST)-MD5) authentication failed
### failregex = (?i): warning: [-._\w]+\[<HOST>\]: SASL (?:LOGIN|PLAIN|(?:CRAM|DIGEST)-MD5) authentication failed(: [ A-Za-z0-9+/]*={0,2})?\s*$

ignoreregex = authentication failed: Connection lost to authentication server$

[Init]

journalmatch = _SYSTEMD_UNIT=postfix@-.service
#journalmatch = _SYSTEMD_UNIT=postfix.service

# Author: Yaroslav Halchenko
# Modified by walter@hofstaedtler.com
